# Generated by Django 4.1.5 on 2023-01-12 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='caste',
            field=models.CharField(choices=[('Gen', 'General'), ('OBC', 'Other Backward Class (OBC)'), ('PVTG', 'Particularly Vulnerable Tribal Group (PVTG)'), ('SC', 'Scheduled Caste (SC)'), ('ST', 'Scheduled Tribe (ST)')], max_length=4),
        ),
        migrations.AlterField(
            model_name='profile',
            name='disable',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('T', 'Transgender')], max_length=1),
        ),
    ]
