# Generated by Django 4.1.7 on 2023-04-05 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_employement_alter_profile_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_current',
            field=models.BooleanField(default=True),
        ),
    ]
