# Generated by Django 4.1.7 on 2023-03-16 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profile_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bpl',
            field=models.CharField(choices=[('T', 'True'), ('F', 'False')], default='True', max_length=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='disable',
            field=models.CharField(choices=[('T', 'True'), ('F', 'False')], default='True', max_length=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('T', 'Transgender')], default='Female', max_length=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='martial_status',
            field=models.CharField(choices=[('M', 'Married'), ('U', 'Unmarried'), ('D', 'Divorced'), ('W', 'Widowed')], max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='student',
            field=models.CharField(choices=[('T', 'True'), ('F', 'False')], default='True', max_length=1),
        ),
    ]
