# Generated by Django 4.1.7 on 2023-03-21 17:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=255)),
                ('details', models.TextField()),
                ('image', models.ImageField(default='default.jpg', upload_to='schemes')),
                ('date', models.DateTimeField()),
                ('uploadDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('slug', models.SlugField(unique=True)),
                ('tags', models.CharField(blank=True, max_length=200, null=True)),
                ('source', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'News',
            },
        ),
    ]
