# Generated by Django 4.1.7 on 2023-03-02 17:56

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schemes',
            name='details',
            field=tinymce.models.HTMLField(),
        ),
    ]
