# Generated by Django 4.1.7 on 2023-04-02 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schemes',
            name='isExpired',
            field=models.BooleanField(default=1),
        ),
    ]
