# Generated by Django 4.1.7 on 2023-04-04 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0002_schemes_isexpired'),
    ]

    operations = [
        migrations.AddField(
            model_name='schemes',
            name='applicationProcess',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='schemes',
            name='benefits',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='schemes',
            name='documentsRequired',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='schemes',
            name='isExpired',
            field=models.BooleanField(default=False),
        ),
    ]
