# Generated by Django 4.1.7 on 2023-03-03 01:08

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0002_alter_schemes_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schemes',
            name='details',
            field=django_quill.fields.QuillField(blank=True),
        ),
    ]
