# Generated by Django 4.1.7 on 2023-04-09 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0003_schemes_applicationprocess_schemes_benefits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ministry',
            name='image',
            field=models.URLField(default='https://static.thenounproject.com/png/4592332-200.png'),
        ),
    ]
