# Generated by Django 4.1.7 on 2023-03-03 01:26

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0003_alter_schemes_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schemes',
            name='details',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
