# Generated by Django 4.1.7 on 2023-03-18 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0006_state_schemes_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ministry',
            options={'verbose_name_plural': 'Ministries'},
        ),
        migrations.AlterModelOptions(
            name='schemes',
            options={'verbose_name': 'Scheme', 'verbose_name_plural': 'Schemes'},
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
