# Generated by Django 4.1.7 on 2023-03-18 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0007_alter_ministry_options_alter_schemes_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.URLField(default='https://cdn.myscheme.in/images/icons/check.svg'),
        ),
    ]
