# Generated by Django 4.1.7 on 2023-04-05 10:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        ('schemes', '0003_schemes_applicationprocess_schemes_benefits_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schemes.schemes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
        ),
    ]
