# Generated by Django 4.1.7 on 2023-04-09 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_is_current'),
        ('recommendation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendscheme',
            name='user',
            field=models.ForeignKey(limit_choices_to={'is_current': True}, on_delete=django.db.models.deletion.CASCADE, to='profiles.profile'),
        ),
        migrations.AddConstraint(
            model_name='recommendscheme',
            constraint=models.UniqueConstraint(fields=('user', 'scheme'), name='unique recommendation'),
        ),
    ]
