# Generated by Django 4.1.7 on 2023-04-06 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='recommendscheme',
            constraint=models.UniqueConstraint(fields=('user', 'scheme'), name='unique recommendation'),
        ),
    ]
